### PR TITLE
Add entry for application/x-ms-dos-executable

### PR DESCRIPTION
**Pull request by YoranBrondsema**

### CODE REVIEW

**Comment by halostatue** [comment]
Hi. This change itself is fine, but note that the `exe` extension is also associated with `application/octet-stream`, `application/x-msdos-program`, and `application/x-msdownload`. I don’t think it should be removed from `x-ms-dos-program` or `x-msdownload`, but we may want to remove it from `application/octet-stream`.

**Comment by YoranBrondsema** [comment]
@halostatue Thanks for the quick reply. I removed the `exe` extension from `application/octet-stream`.

Also, I wasn't sure what to put as `encoding` for `application/x-ms-dos-executable`. From what I see, most encodings in `application.yaml` are set to `base64`. But I'm not sure that a Windows executable is encoded in base64? Rather than putting something wrong, I left it empty, assuming that `mime-types-data` can cope with MIME types without an encoding specified.

**Comment by halostatue** [comment]
The default encoding for `application/*` is `base64` IIRC, but I’d have to check. I’ll merge this and release it over the holidays, so you should see it for January.

**Comment by YoranBrondsema** [comment]
Great, thanks! Happy holidays.

**Pull request merged**
